# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d7bec2bfccffed89ccb59b1dc47b32f7839d0c045b70c0540f49539ed585c9e59781a608b2be2bbabb79108f95e86232cb27a2f8adbf621393c2c783ee6f847
  stripe_publishable_key: pk_test_NQANw7AsGBQ3GvXgIWE47bdk
  stripe_secret_key: sk_test_5vffV257fef96Ok4yiwX4VMI

test:
  secret_key_base: c0f33f6682610d404921683704d610ac4f8b4260a45dbadd73ce19ed39b2fc9fb77837dcf44d2c5f9958b0a49e493c0eff5fea9e5b83532861b4fc344413283b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_publisable_key: ENV['stripe_publishable_key']
  stripe_secret_key: ENV['stripe_publishable_key']
